[build]
  base = "."
  command = "pnpm install && turbo run build --filter web"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[plugin_settings.netlify-plugin-nextjs]
  output = "apps/web/.next"